/**
 * @file mod_rc_semantic.h
 * @brief RC Semantic Mapping Module (L3)
 * @note  Pure logic layer. Converts raw CRSF channels into high-level system
 *        intents. Strictly no floating-point math. No hardware calls.
 */

#ifndef MOD_RC_SEMANTIC_H
#define MOD_RC_SEMANTIC_H

#include "ara_def.h"
#include "datahub.h"

/* =========================================================
 * 1. Logic & Timing Constants
 * ========================================================= */

/**
 * @brief Pulse width of the synthetic system-reset pulse generated by SB.
 * @note  SB now uses edge-triggered single pulse semantics.
 */
#define MOD_RC_SB_PULSE_HOLD_MS      (150U)

/**
 * @brief CH1 incremental step: stick outside deadband triggers a step
 *        immediately, then every STEP_INTERVAL_MS while held.
 */
#define MOD_RC_CH1_DEADBAND_PCT       (15)
#define MOD_RC_CH1_STEP_INTERVAL_MS   (40U)
#define MOD_RC_CH1_STEP_DEG           (8)

/**
 * @brief CH1 threshold for entering EXTEND state.
 */
#define MOD_RC_CH1_ENTER_EXTEND_PCT  (55)

/**
 * @brief CH1 threshold for entering RETRACT state.
 */
#define MOD_RC_CH1_ENTER_RETRACT_PCT (-55)

/**
 * @brief CH1 absolute threshold for returning to HOLD state.
 */
#define MOD_RC_CH1_EXIT_HOLD_ABS_PCT (35)

/**
 * @brief CH2 gripper center deadband (raw counts). Spring-centered stick
 *        rests around RAW_MID with mild ADC noise. ±30 raw ≈ ±3.3 deg
 *        of stick travel — small enough to feel 1:1, large enough to
 *        suppress visible jitter when idle.
 */
#define MOD_RC_CH2_CENTER_DEADBAND_RAW (30U)

/* Channel Mapping Indices (CRSF array is 0-indexed) */
#define MOD_RC_IDX_CH1 0U  /**< CH1: Stick RX axis (main arm incremental intent). */
#define MOD_RC_IDX_CH2 1U  /**< CH2: Spring-centered gripper servo axis. */
#define MOD_RC_IDX_SA  4U  /**< CH5: Mode request switch (2-pos). */
#define MOD_RC_IDX_SC  6U  /**< CH7: Gripper switch (3-pos). */
#define MOD_RC_IDX_SF  7U  /**< CH8: Roll attitude wheel. */
#define MOD_RC_IDX_SB  8U  /**< CH9: System reset switch (3-pos). */
#define MOD_RC_IDX_SD  9U  /**< CH10: E-stop switch (2-pos). */

/* CRSF thresholds */
#define MOD_RC_VAL_MIN 172U
#define MOD_RC_VAL_MAX 1811U
#define MOD_RC_VAL_MID 992U
#define MOD_RC_SW_LOW  600U
#define MOD_RC_SW_HIGH 1400U

/* =========================================================
 * 2. Debug Output Structure
 * ========================================================= */

/**
 * @brief Debug-oriented RC output used by TB0 direct module debugging.
 * @note  This structure intentionally carries low-level analog observables
 *        without collapsing CH1 into EXTEND / RETRACT / HOLD semantics.
 */
typedef struct {
    bool     is_link_up;       /**< Link state filled by L4 task wrapper. */
    uint8_t  req_mode;         /**< Requested system mode (ARA_MODE_*). */
    uint8_t  estop_state;      /**< E-stop state (ESTOP_*). */
    int16_t  ch1_percent;      /**< CH1 normalized to [-100, +100]. */
    uint16_t aux_knob_val;     /**< CH8 / SF wheel normalized to [0, 1000]. */
    bool     sys_reset_pulse;  /**< Edge-triggered SB pulse. */

    /* --- 新增：专门用于标定的绝对角度语义 --- */
    uint8_t  roll_angle;       /**< Mapped from CH8 / SF wheel, [0, 180] deg. */
    uint8_t  gripper_angle;    /**< Mapped from CH2 spring axis, [0, 180] deg. */
} RcDebugAnalogData_t;

/* =========================================================
 * 3. Module Context Structure
 * ========================================================= */

/**
 * @brief RC semantic module runtime context.
 */
typedef struct {
    AraArmCmd_t arm_last_cmd;      /**< CH1 hysteresis latch state. */
    uint8_t     sb_last_pos;       /**< Last decoded SB position. */
    uint32_t    sb_pulse_start_ms; /**< Tick when current SB pulse started. */
    bool        sb_pulse_active;   /**< Whether SB pulse is currently active. */

    /* CH1 incremental stepping */
    int16_t     inc_target_deg;    /**< Accumulated incremental target angle. */
    uint32_t    inc_last_step_ms;  /**< Tick of last step, 0 = take first step immediately. */
} ModRcSemantic_Context_t;

/* =========================================================
 * 4. Module API
 * ========================================================= */

/**
 * @brief  Initialize RC semantic module.
 * @param  p_ctx Pointer to module context.
 * @param  initial_chs Initial raw channel snapshot.
 * @return ARA_OK on success, otherwise ARA_ERR_PARAM.
 */
AraStatus_t ModRcSemantic_Init(ModRcSemantic_Context_t *p_ctx,
                               const uint16_t *initial_chs);

/**
 * @brief  Convert raw RC channels into formal semantic intent.
 * @param  p_ctx Pointer to module context.
 * @param  channels Raw channel array.
 * @param  current_tick_ms Current system tick.
 * @param  out_data Output semantic intent.
 * @return ARA_OK on success, otherwise ARA_ERR_PARAM.
 */
AraStatus_t ModRcSemantic_Process(ModRcSemantic_Context_t *p_ctx,
                                  const uint16_t *channels,
                                  uint32_t current_tick_ms,
                                  RcControlData_t *out_data);

/**
 * @brief  Convert raw RC channels into debug-oriented analog observables.
 * @param  p_ctx Pointer to module context.
 * @param  channels Raw channel array.
 * @param  current_tick_ms Current system tick.
 * @param  out_data Output debug RC data.
 * @return ARA_OK on success, otherwise ARA_ERR_PARAM.
 */
AraStatus_t ModRcSemantic_ProcessDebugAnalog(ModRcSemantic_Context_t *p_ctx,
                                             const uint16_t *channels,
                                             uint32_t current_tick_ms,
                                             RcDebugAnalogData_t *out_data);

/**
 * @brief  Reseed the CH1 incremental accumulator to a known angle.
 * @note   Call this when exiting force mode or after a mode switch to
 *         prevent the incremental target from jumping away from the
 *         servo's current physical position.
 */
void ModRcSemantic_ReseedIncremental(ModRcSemantic_Context_t *p_ctx,
                                     int16_t current_deg);

#endif /* MOD_RC_SEMANTIC_H */
